#
# Maël Valais <mael.valais@gmail.com>
#
# This Travis-ci configuration file has been writen to automate
# the building process and make deploying the application easy.
# for the platforms Linux and Mac OS X.
#
# The travis-ci servers are going to run this script on any push
# to the repo. Basically, it
# - tells the author of a commit if his commit has broken the build,
# - deploys two .zip containing the linux and osx apps, with the
#   touist compiled in it
#
# To allow Travis-ci to know that something has been pushed to the repo
# the owner of the project (Olivier Lezaud back then) had had to link
# the repo to the Travis-ci website.
#
# vim:set et sw=2 ts=2:


language: java
os:
  - linux
  - osx
# Install packages using apt-get on linux environment
addons:
  apt:
    sources:
    - avsm
    packages:
    - opam

cache:
  apt: true
  directories:
    - $HOME/.opam

before_install:
  # Install packages using brew on osx environment
  - javac -version
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew install opam ant; fi
  - opam init --auto-setup
  - eval `opam config env`
  - opam install --yes ocamlfind menhir fileutils minisat
  - opam pin add -y yices2 "https://github.com/maelvalais/ocamlyices2.git#v0.0.2"
  # Put the dependency yices-smt2 to external/
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then file=yices-2.4.2-x86_64-apple-darwin15.2.0-static-gmp.tar.gz; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then file=yices-2.4.2-x86_64-unknown-linux-gnu-static-gmp.tar.gz; fi
  - echo $file
  - curl -o yices.tar.gz "http://yices.csl.sri.com/cgi-bin/yices2-newnewdownload.cgi?file=${file}&accept=I+Agree"
  - tar xzf yices.tar.gz
  - cp yices-*/bin/yices-smt2 support/gui/external
install:
  # Build touist
  - cd $TRAVIS_BUILD_DIR
  - ./configure --bindir support/gui/external --enable-tests
  - make && make install

  # Build the Java GUI touist.jar (in support/gui)
  - cd $TRAVIS_BUILD_DIR/support/gui
  - chmod ugo+x external/touist
  - ant -e zip
  - zip=$(ls | grep 'touist.*\.zip' | head -1) # The artifact's name for later use
  - echo $zip && cd $TRAVIS_BUILD_DIR

# This part is meant for unit tests (among others).
script:
  - cd $TRAVIS_BUILD_DIR
  - make test

before_deploy:
  - cd $TRAVIS_BUILD_DIR
# This is the part where the touist.zip is pushed to the Github
# Releases. It will only do so when we create new tags, like v1.1.2.
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    # This is maelvalais's ciphered credentials.
    # It has been ciphered by travis's encryption system.
    secure: PNvSXUUBTgQjfio2QL9qQYtV8JCpT6nWkvRNDGFoAwdskusi719jRLjGYDKHrTHelxiehepKSxiFcPcOCfFD/WkfOLZvEBs463Xb3fldoNxUgRAWwYy/uEWwlD3lbSBREgtqrfuHP3uVKF7tYDlJXhTFpdM/nuwXGIwU5AuUhCw=
  file: support/gui/$zip
  on:
    branch: master
    tags: true

# The commiter will be informed that one of his commits
# broke the build. I didn't want us to receive an email
# each time we did a new branch, so I changed to 
#     on_success: never
notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
